### ISSUE TITLE
2.0 Refresh

### ISSUE THREAD

**Issue by nhagen** [nhagen/react-intercom#73]
Hey Folks,

This package hasn't gotten a ton of attention from me lately, but a number of issues have come up that needed to be addressed. I was able to find some time today and migrated the build system to rollup, and the component itsself to a functional component using hooks.

This means there were some significant API changes, and thus a 2.0 branch/tag, and a new 2.0 alpha release on NPM.

The biggest changes are (a) that now _both_ exports of this package are now named exports, and (b) the package is now more strict about the props that are passed in.

There are also improvements to the TS types, and probably some other things. Happy to document anything that I've forgotten to mention here. Please leave a comment or submit a PR if you find anything worth documenting.

You can read documentation on the alpha release by looking at the [2.0 branch]() or [2.0.0-alpha.1](https://github.com/nhagen/react-intercom/tree/v2.0.0-alpha.1) release.

You can try out the latest 2.0 release by installing `react-intercom@next`. This should be more or less ready to be released, but I want to get some eyes on it to confirm there aren't any issues.

Once I feel confident there won't be any issues, I'll merge this into master and push an official v2.0.0 release.

**Comment by suhlob** [comment]
@nhagen you can open issue here - https://github.com/suhlob/react-intercom-widget/issues

**Comment by nikparo** [comment]
IntercomAPI secondary arguments don't get passed through correctly. I've opened a pull request: https://github.com/nhagen/react-intercom/pull/77

**Comment by andrewjrhill** [comment]
Type mismatch on `hide_default_launcher`. I have opened a pull request: https://github.com/nhagen/react-intercom/pull/76

**Comment by bluepeter** [comment]
@nhagen any chance we can these PRs merged and a new 2.0 release?

**Comment by vfonic** [comment]
Ping @nhagen!

Thanks for the great work! Perhaps you should add to current `master` `README.md` about this issue/pre-release?

I've stumbled upon this by mere luck. I saw last commit on master is from Oct 25th 2018 and was about to move on and skip using this package...

**Comment by BAPopov** [comment]
Hey @nhagen ,, great work, do you have any plans of releasing the 2.0 version and if you do when?

**Comment by andrewjrhill** [comment]
Would be nice if we could get @fvoordeckers PR released before the 2.0 goes out so we can get back our consoles. https://github.com/nhagen/react-intercom/pull/84

**Comment by danvernon** [comment]
Any updates on 2.0?

**Comment by ChristianJacobsen** [comment]
At this point I feel like it is no longer in @nhagen's interest to continue driving this product forward. There are several open pull requests, and I believe it would be in everyone's interest if either a new, definite fork of the project is made, that @nhagen gives a different maintainer access to merge contributions into the repo, or that the ownership is transferred.

I have no problems understanding that people are busy, but maybe he/she/x should then pass the baton to someone else who has time to maintain/merge contributions.

**Comment by bluepeter** [comment]
Two thumbs up to that.

I sent him an email...

**Comment by Morsmetus** [comment]
Any updates on release 2.0?

**Comment by bluepeter** [comment]
Anyone want to fork? No reply from the maintainer...

**Comment by devrnt** [comment]
I'm keen to announce that I've released a React Intercom integration:   
https://github.com/devrnt/react-use-intercom

I don't want to spam this issue with advertisement, that's why I'll delete this message in the near future.

**Motivation**
I've found it not very developer friendly to integrate Intercom in a React application.

**Comment by andrewjrhill** [comment]
It would be great if NPM and GitHub flagged projects as "dormant" if outstanding issues see no feedback from contributors/maintainers after a few weeks. 

The fact that this repo is still seeing over 40,000 downloads a week with no active maintainers is pretty alarming.

**Comment by vfonic** [comment]
@andrewjrhill I fully agree with you. That's one of the flaws of open-source software. Other two big issues that I see are:
1) Funding
2) Taking over inactive projects

That being said, your comment written here (just like mine), provides no benefit to this repo nor to the idea you expressed in it. Perhaps a better channel to deliver your message would be by writing to GitHub employees on twitter and I believe I saw somewhere that they have some GitHub repo for suggestions (or I'm making stuff up now 🤔).

**Comment by goamn** [comment]
@devrnt Thanks Jonas this is great! Please don't delete the post as it was the only way I found out about it. I think it would be great if you could contact Intercom and have your package listed instead of this one (on this page: https://www.intercom.com/help/en/articles/170-integrate-intercom-in-a-single-page-app ).
